### ISSUE TITLE
[Feature Request]: Can I use bukkit's "Material" method to identify ftbquest:book?

### ISSUE THREAD

**Issue by glowingstone124** [FTBTeam/FTB-Mods-Issues#1008]
### Mod

Ftbquest

### Description

When I trying to give player a ftbquest:book item by bukkit plugin, it encountered an error:
```
Caused by: java.lang.IllegalArgumentException: Material cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23147!/:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:84) ~[forge-1.20.1-47.1.79-universal.jar%23365!/:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:72) ~[forge-1.20.1-47.1.79-universal.jar%23365!/:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:60) ~[forge-1.20.1-47.1.79-universal.jar%23365!/:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[forge-1.20.1-47.1.79-universal.jar%23365!/:?]
        at org.qo.oregano.JoinLeaveListener.onPlayerJoin(JoinLeaveListener.java:31) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.1.79-universal.jar%23365!/:?]
        ... 15 more
```

### Describe the solution you'd like

Material are controled by bukkit api, but can you guys fixed it by add ftbquest to Minecraft's current item mappings?

**Comment by desht** [comment]
Sorry, using Bukkit in conjunction with Forge mods is in no way supported by us.  There are plenty of ways to give a player an item without needing a Bukkit, _especially_ in a Forge environment. So no.
