### ISSUE TITLE
[Bug]: client crash when opening FTB Quests related GUI

### ISSUE THREAD

**Issue by JaffaJace** [FTBTeam/FTB-Mods-Issues#113]
### Mod

FTB Quests

### Mod version

FTBQuests-1202.9.0.15

### Forge / Fabric version

1.12.2 14.23.5.2855

### What issue are you having?

Me and a few friends have a "modpack" (just a few mods we bunched together that we enjoy) that we play on, and we've been using FTB Quests since the start and its been working normally, but after I travelled to the Moon dimension from Galacticraft, all the task/progress screens were blank and everytime i right-clicked a task screen or opened the Quest menu (either through button in top-left or quest book), my game would freeze and crash shortly after. At first i suspected it was mod incompatibility but one of my friends has the same problem although they hadn't travelled to any Galacticraft dimension yet.

### Crashlogs

[debug.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/7513073/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/7513076/latest.log)

### Steps to reproduce

I honestly do not know how to recreate this bug, although it crashes my game every time, no matter what i do
All i know is that i had an existing questline, i travelled to the Galacticraft moon, and then i clicked the quests button

### Anything else to note?

I don't know if this has any link, but the world is a superflat.

**Comment by Raidobw2** [comment]
Stacktrace for dev:
```
Thread: Client thread
Stacktrace:
	at com.feed_the_beast.ftbquests.client.FTBQuestsClientEventHandler.onCustomClick(FTBQuestsClientEventHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_217_FTBQuestsClientEventHandler_onCustomClick_CustomClickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.feed_the_beast.ftblib.lib.EventBase.post(EventBase.java:20)
	at com.feed_the_beast.ftblib.lib.gui.GuiBase.handleClick(GuiBase.java:529)
	at com.feed_the_beast.ftblib.lib.gui.Widget.handleClick(Widget.java:214)
	at com.feed_the_beast.ftblib.client.SidebarButton.onClicked(SidebarButton.java:181)
	at com.feed_the_beast.ftblib.client.FTBLibClientEventHandler$GuiButtonSidebarGroup.func_146116_c(FTBLibClientEventHandler.java:596)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:435)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
```

**Comment by Binomialgeoduck** [comment]
So did anyone figure out how to fix this? I am currently having this problem in my pack as well.

**Comment by Zeyu-Li** [comment]
I have a similar issue with MC Eternal lite but it relates to completing one of the tasks

**Comment by Zeyu-Li** [comment]
Upon further investigation I believe it is this one that is the issue: 
![image](https://user-images.githubusercontent.com/34993025/209243497-70e1e00b-ae51-4661-a1b7-a88e7a14a4e9.png)

Maybe it's check is causing the game to crash
