### ISSUE TITLE
[Bug]: Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:minecraft:zombie

### ISSUE THREAD

**Issue by ModernGamingWorld** [FTBTeam/FTB-Mods-Issues#1232]
### Mod

FTB Quests

### Mod version

ftb-quests-neoforge-2100.1.0

### Forge / Fabric version

1.21 21.0.21

### What issue are you having?

Try to use my quests book from 1.19.2 and it crashed, read the changelog and it did not state anywhere we had to rewrite our quests book to make it work. If thats the case this is going to be very hard for some modpack devs

### Crashlogs

Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.quest.task.TaskType.createTask(TaskType.java:54) ~[ftb-quests-neoforge-2100.1.0.jar%23378!/:2100.1.0] {re:classloading}
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.quest.BaseQuestFile.lambda$readDataFull$11(BaseQuestFile.java:619) ~[ftb-quests-neoforge-2100.1.0.jar%23378!/:2100.1.0] {re:classloading}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.quest.BaseQuestFile.readDataFull(BaseQuestFile.java:592) ~[ftb-quests-neoforge-2100.1.0.jar%23378!/:2100.1.0] {re:classloading}
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.quest.ServerQuestFile.load(ServerQuestFile.java:77) ~[ftb-quests-neoforge-2100.1.0.jar%23378!/:2100.1.0] {re:classloading}
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.FTBQuestsEventHandler.serverStarted(FTBQuestsEventHandler.java:83) ~[ftb-quests-neoforge-2100.1.0.jar%23378!/:2100.1.0] {re:classloading}
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?] {re:mixin}
	at TRANSFORMER/architectury@13.0.1/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.1-neoforge.jar%23328!/:?] {re:classloading}
	at TRANSFORMER/architectury@13.0.1/dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-13.0.1-neoforge.jar%23328!/:?] {re:classloading}
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar%23122!/:?] {}
	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy104.stateChanged(Unknown Source) ~[?:?] {}
	at TRANSFORMER/architectury@13.0.1/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:97) ~[architectury-13.0.1-neoforge.jar%23328!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23106!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23106!/:?] {}
	at TRANSFORMER/neoforge@21.0.21-beta/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:98) ~[neoforge-21.0.21-beta-universal.jar%23318!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithostitched.neoforge.mixins.json:common.ServerLifecycleHooksMixin from mod lithostitched,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[client-1.21-20240613.152323-srg.jar%23317!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23317!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:minecraft:zombie
	at TRANSFORMER/minecraft@1.21/net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284) ~[client-1.21-20240613.152323-srg.jar%23317!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entity_texture_features-common.mixins.json:MixinIdentifier from mod entity_texture_features,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin from mod ftblibrary,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:60) ~[client-1.21-20240613.152323-srg.jar%23317!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entity_texture_features-common.mixins.json:MixinIdentifier from mod entity_texture_features,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin from mod ftblibrary,pl:mixin:A}
	at TRANSFORMER/ftbquests@2100.1.0/dev.ftb.mods.ftbquests.quest.task.KillTask.<clinit>(KillTask.java:29) ~[?:?] {re:classloading}
	... 27 more

### Steps to reproduce

1. Added Mod
2. Added bk my custom ftb quests
3. launched modpack
4. crash

**Comment by desht** [comment]
1. Please don't put stacktraces directly in a problem report. Paste sites exist for a reason
2. Without seeing your actual quest book data, I can't tell what your problem is.

**Comment by ModernGamingWorld** [comment]
if you mean the data.snbt file, its the same as 1.19.2, as I copied and pasted my whole quest book over from 1.19.2, as I have not had any issues doing that till now in NeoForge 1.21 version of FTB Quests

**Comment by desht** [comment]
**I need to see you quest book file**

**Comment by ModernGamingWorld** [comment]
How do I plan to provide that when currently its attached to my custom Modpack, Id hate to upload all my quests here and then have someone else see them and download them

**Comment by desht** [comment]
That'll do fine, thanks.  (You realise, I hope, that anyone can just see them and download them from there too, right?)

**Comment by ModernGamingWorld** [comment]
okay

**Comment by desht** [comment]
Fixed in 2100.1.1
