### ISSUE TITLE
[Feature Request]: FTB Ranks Fabric 1.20.1 version is no where to find

### ISSUE THREAD

**Issue by DavidKitano** [FTBTeam/FTB-Mods-Issues#1241]
### Mod

FTB Ranks

### Description

I do remember FTB Ranks is available for Fabric 1.20.1, but I find no where to attach that version of mod. Is it no longer supported?

btw I manully changed the JSON file in 1.20.4 version of the mod to make it work on my server, however it showed some issues which I assumed it's because the wrong version

- Can't message (Chain link failed, continuing to next one)
```
27.06 04:34:26 [服务器] 服务器 thread/ERROR Chain link failed, continuing to next one
27.06 04:34:26 [服务器] 信息 java.lang.AbstractMethodError: Receiver class dev.ftb.mods.ftbranks.fabric.FTBRanksFabric$$Lambda$8823/0x0000000801ecdd98 does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture decorate(net.minecraft.class_3222, net.minecraft.class_2561)' of interface net.minecraft.class_7492.
27.06 04:34:26 [服务器] 信息 at net.fabricmc.fabric.api.message.v1.ServerMessageDecoratorEvent.lambda$static$2(ServerMessageDecoratorEvent.java:88) ~[fabric-message-api-v1-5.1.9+1802ada577-1e4cd12262aa224a.jar:?]
27.06 04:34:26 [服务器] 信息 at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
27.06 04:34:26 [服务器] 信息 at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
27.06 04:34:26 [服务器] 信息 at net.fabricmc.fabric.api.message.v1.ServerMessageDecoratorEvent.lambda$static$3(ServerMessageDecoratorEvent.java:88) ~[fabric-message-api-v1-5.1.9+1802ada577-1e4cd12262aa224a.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.mde0f838$fabric-message-api-v1$lambda$onGetChatDecorator$0$4(MinecraftServer.java:5323) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
27.06 04:34:26 [服务器] 信息 at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.mde0f838$fabric-message-api-v1$lambda$onGetChatDecorator$1$3(MinecraftServer.java:5323) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_3244.method_44900(class_3244.java:1297) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
27.06 04:34:26 [服务器] 信息 at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
- Can't use some specific command, e.g. /say
```
27.06 04:45:00 [服务器] 服务器 thread/ERROR Task failed
27.06 04:45:00 [服务器] 信息 java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class dev.ftb.mods.ftbranks.fabric.FTBRanksFabric$$Lambda$8823/0x0000000801ecdd98 does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture decorate(net.minecraft.class_3222, net.minecraft.class_2561)' of interface net.minecraft.class_7492.
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194) ~[?:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
27.06 04:45:00 [服务器] 信息 at net.fabricmc.fabric.api.message.v1.ServerMessageDecoratorEvent.lambda$static$3(ServerMessageDecoratorEvent.java:88) ~[fabric-message-api-v1-5.1.9+1802ada577-1e4cd12262aa224a.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.mde0f838$fabric-message-api-v1$lambda$onGetChatDecorator$0$4(MinecraftServer.java:5323) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.mde0f838$fabric-message-api-v1$lambda$onGetChatDecorator$1$3(MinecraftServer.java:5323) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_2196.method_45566(class_2196.java:55) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_2196.method_45562(class_2196.java:46) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_3110.method_13563(class_3110.java:22) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_2170.redirect$zhj000$architectury$performCommand(class_2170.java:1545) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_3244.method_45010(class_3244.java:1341) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_3244.method_44356(class_3244.java:1321) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
27.06 04:45:00 [服务器] 信息 at java.lang.Thread.run(Thread.java:833) ~[?:?]
27.06 04:45:00 [服务器] 信息 Caused by: java.lang.AbstractMethodError: Receiver class dev.ftb.mods.ftbranks.fabric.FTBRanksFabric$$Lambda$8823/0x0000000801ecdd98 does not define or inherit an implementation of the resolved method 'abstract java.util.concurrent.CompletableFuture decorate(net.minecraft.class_3222, net.minecraft.class_2561)' of interface net.minecraft.class_7492.
27.06 04:45:00 [服务器] 信息 at net.fabricmc.fabric.api.message.v1.ServerMessageDecoratorEvent.lambda$static$2(ServerMessageDecoratorEvent.java:88) ~[fabric-message-api-v1-5.1.9+1802ada577-1e4cd12262aa224a.jar:?]
27.06 04:45:00 [服务器] 信息 at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
27.06 04:45:00 [服务器] 信息 ... 29 more
```

**Comment by desht** [comment]
FTB Ranks 1.20.1 is available, but interestingly never had a non-alpha release.  You can get it here: https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-fabric/files/4596741 - it should work fine.

I'll look at getting a full release out for it, or getting the above version promoted to release status.

**Comment by DavidKitano** [comment]
> FTB Ranks 1.20.1 is available, but interestingly never had a non-alpha release. You can get it here: https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-fabric/files/4596741 - it should work fine.
> 
> I'll look at getting a full release out for it, or getting the above version promoted to release status.

Thanks, I'll try this one later

**Comment by desht** [comment]
This is now marked a full release, so should be visible to the app & web gui now.
