### ISSUE TITLE
[Bug]: quest book crashes client if `ClientQuestFile` is missing

### ISSUE THREAD

**Issue by Quezler** [FTBTeam/FTB-Mods-Issues#126]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.5-build.72.jar

### Forge / Fabric version

forge-1.16.5-36.2.8-client.jar

### Modpack & version

Cave Factory 1.0.2

### What issue are you having?

for whatever reason the quest book isn't always synced to the clients on that modpack.

if you use the quest book it doesn't check [if the instance exists](https://github.com/FTBTeam/FTB-Quests/blob/main/common/src/main/java/dev/ftb/mods/ftbquests/client/FTBQuestsClient.java#L230) but just crashes you silently.

the button in your inventory [does check it](https://github.com/FTBTeam/FTB-Quests/blob/dev/common/src/main/java/dev/ftb/mods/ftbquests/client/FTBQuestsClientEventHandler.java#L100) (although not with the method shown above) & shows a small popup accordingly (which doesn't fit all text btw)

it didn't occur to me at all on my previous run of the pack (but it did affect my friend with whom i played), assuming it might sometimes affect the first player that connected? `¯\_(ツ)_/¯`

### Crashlogs

```
java.lang.NullPointerException: Unexpected error
	at dev.ftb.mods.ftbquests.client.FTBQuestsClient.openGui(FTBQuestsClient.java:245) ~[ftbquests:1605.3.5-build.72] {re:classloading}
	at dev.ftb.mods.ftbquests.item.QuestBookItem.func_77659_a(QuestBookItem.java:35) ~[ftbquests:1605.3.5-build.72] {re:classloading}
```

### Steps to reproduce

setup a server and join as client until it refuses to load the quests 🙃 

### Anything else to note?

gui scale 3

**Comment by MichaelHillcox** [comment]
As this issue is very old and we've pushed a large amount of changes to the mod. Please check if your issue is still present in 1.21 versions of the mod. If it is, please open a new issue with updated information so it's top of our list 👍
