### ISSUE TITLE
[Bug]: 1.20.1Fabric

### ISSUE THREAD

**Issue by ljt1477059273** [FTBTeam/FTB-Mods-Issues#1277]
### Mod

ftb-quests

### Mod version

ftb-quests-fabric-2001.3.5

### Forge / Fabric version

1.20.1

### What issue are you having?

```
[23:39:39] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.ServerQuestFile.load()" because "dev.ftb.mods.ftbquests.quest.ServerQuestFile.INSTANCE" is null
	at dev.ftb.mods.ftbquests.FTBQuestsEventHandler.serverStarted(FTBQuestsEventHandler.java:81) ~[ftb-quests-fabric-2001.3.5.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar:?]
	at jdk.proxy2.$Proxy187.stateChanged(Unknown Source) ~[?:?]
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$9(EventHandlerImpl.java:65) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-64bb13225b65065c.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ccl000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:6842) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:39:39] [Server thread/ERROR]: This crash report has been saved to: D:Fabric-Server\.\crash-reports\crash-2024-07-17_23.39.39-server.txt
[23:39:39] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.ServerQuestFile.saveNow()" because "dev.ftb.mods.ftbquests.quest.ServerQuestFile.INSTANCE" is null
	at dev.ftb.mods.ftbquests.FTBQuestsEventHandler.serverStopped(FTBQuestsEventHandler.java:85) ~[ftb-quests-fabric-2001.3.5.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar:?]
	at jdk.proxy2.$Proxy187.stateChanged(Unknown Source) ~[?:?]
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$10(EventHandlerImpl.java:66) ~[%5Bapi%5Darchitectury-9.1.12-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-64bb13225b65065c.jar:?]
	at net.minecraft.server.MinecraftServer.handler$ccl000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:6847) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

None

**Comment by desht** [comment]
I need to see your complete logfile, from starting the game to when the crash occurs.  (Please post it to a paste site, _not_ straight into the issue)
