### ISSUE TITLE
[Bug]: ftb ultmine doesnt work on servers

### ISSUE THREAD

**Issue by Chuunkyz** [FTBTeam/FTB-Mods-Issues#189]
### Mod

FTB Ultimine

### Mod version

ftb-ultimine-fabric-1801.3.2-build.48

### Forge / Fabric version

0.12.12 or 0.13.1 (same issue)

### What issue are you having?

starting a server with the mod crashes

### Crashlogs

[17:50:20] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ftbultimine'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400) ~[?:?]
at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42) ~[?:?]
at dev.ftb.mods.ftblibrary.snbt.config.ConfigUtil.lambda$loadDefaulted$0(ConfigUtil.java:42) ~[ftb-library-fabric-1801.3.5-build.109.jar:?]
at dev.ftb.mods.ftblibrary.snbt.config.SNBTConfig.load(SNBTConfig.java:145) ~[ftb-library-fabric-1801.3.5-build.109.jar:?]
at dev.ftb.mods.ftblibrary.snbt.config.ConfigUtil.loadDefaulted(ConfigUtil.java:38) ~[ftb-library-fabric-1801.3.5-build.109.jar:?]
at dev.ftb.mods.ftblibrary.snbt.config.ConfigUtil.loadDefaulted(ConfigUtil.java:22) ~[ftb-library-fabric-1801.3.5-build.109.jar:?]
at dev.ftb.mods.ftbultimine.config.FTBUltimineCommonConfig.load(FTBUltimineCommonConfig.java:33) ~[ftb-ultimine-fabric-1801.3.2-build.48.jar:?]
at dev.ftb.mods.ftbultimine.FTBUltimine.(FTBUltimine.java:82) ~[ftb-ultimine-fabric-1801.3.2-build.48.jar:?]
at dev.ftb.mods.ftbultimine.fabric.FTBUltimineFabric.onInitialize(FTBUltimineFabric.java:13) ~[ftb-ultimine-fabric-1801.3.2-build.48.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
... 15 more

### Steps to reproduce

start the server

**Comment by recon88** [comment]
Same here. Crashes on server startup with just Fabric (fabricloader 0.12.12) and the latest FTB Ultimine plus its dependencies installed.
Exact same error.

**Comment by recon88** [comment]
Seems to be an easy/quick fix in FTB Library:
`ftb/mods/ftblibrary/snbt/config/ConfigUtil.java`

`Path ROOT_DIR = Platform.getGameFolder();`
needs to be
`Path ROOT_DIR = Platform.getGameFolder().toAbsolutePath();`

Otherwise `relativize()` in `ROOT_DIR.relativize(configPath)` further down will throw the exception.

I'm not familiar with the git structure of the FTB mods so I'm unable to open a pull request but the fix works fine on my end and the server starts up with the config files being generated.

**Comment by unilock** [comment]
Likely solved by this pull request in Architectury API: https://github.com/architectury/architectury-api/pull/201

**Comment by MaxNeedsSnacks** [comment]
As indicated by @unilock, this should be solved by upgrading to Architectury 3.7
