### ISSUE TITLE
[Bug]: Incompatible with latest Project MMO (Engineer's Life 2)

### ISSUE THREAD

**Issue by flangopink** [FTBTeam/FTB-Mods-Issues#252]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.6-build.98

### Forge / Fabric version

1.16.5 36.2.33

### Modpack & version

Engineer's Life 2 (1.15)

### What issue are you having?

I've played the Engineer's Life 2 modpack before and it worked absolutely fine. The latest version of the modpack has up-to-date FTB Quests and Project MMO, but they cause a crash upon loading.

```
-- Head --
Thread: Render thread
Stacktrace:
	at harmonised.pmmo.ftb_quests.FTBQHandler.<clinit>(FTBQHandler.java:13) ~[pmmo:1.16.5-3.67.6] {re:classloading}
-- MOD pmmo --
Details:
	Mod File: Project_MMO-1.16.5-3.67.6.jar
	Failure message: Project MMO (pmmo) has failed to load correctly
		java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
	Mod Version: 1.16.5-3.67.6
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
Stacktrace:
	at harmonised.pmmo.ftb_quests.FTBQHandler.<clinit>(FTBQHandler.java:13) ~[pmmo:1.16.5-3.67.6] {re:classloading}
	at harmonised.pmmo.ProjectMMOMod.<init>(ProjectMMOMod.java:62) ~[pmmo:1.16.5-3.67.6] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] {}
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.Class.newInstance(Class.java:645) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

```

### Crashlogs

https://paste.ee/p/PJKtt

### Steps to reproduce

1. Install Engineer's Life 2 modpack (1.15).
2. Launch.

**Comment by Raidobw2** [comment]
Hi, ProjectMMO will have to update their code, since it looks like our class names changed. For instance, their integration class `harmonised.pmmo.ftb_quests.FTBQHandler`'s constructor is failing, therefore if they want to fix this they will have to fix their integration methods in order to use our new code.

PMMO does have a Discord server linked on their CurseForge page, I recommending reporting the issue to them that way, since we can't fix it, PMMO is not our project to maintain.
