### ISSUE TITLE
[Bug]: Hitting Schist with the FTB Questbook while it's in an Akashic Tome crashes the game.

### ISSUE THREAD

**Issue by TheButterbrotMan** [FTBTeam/FTB-Mods-Issues#299]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.8-build.101.jar

### Forge / Fabric version

1.18.2 0.16.4

### Modpack & version

Deathdusk - 2.0.8

### What issue are you having?

When i try to hit schist while holding the questbook it crashes the game.

### Crashlogs

https://bytebin.lucko.me/iyO0o4kHzs

### Steps to reproduce

1. Hold Questbook
2. Hit Schist
3. ???
4. Profit

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/92

**Comment by Raidobw2** [comment]
According to the stacktrace and reading the linked issue, it does look like it's either Fabric or something being wrong in the Akashic Tome's data
```
Time: 5/29/22, 4:27 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_33133()" because the return value of "net.minecraft.class_1799.method_7969()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.item.ItemStack.handler$iol000$areTagsEqualReturn2(ItemStack:18168)
	at net.minecraft.item.ItemStack.areNbtEqual(ItemStack:432)
	at net.minecraft.client.network.ClientPlayerInteractionManager.isCurrentlyBreaking(ClientPlayerInteractionManager:286)
	at net.minecraft.client.network.ClientPlayerInteractionManager.updateBlockBreakingProgress(ClientPlayerInteractionManager:224)
	at net.minecraft.client.MinecraftClient.handleBlockBreaking(MinecraftClient:1558)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1923)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1739)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
If you can throw the Quest book out of the Akashic Tome (Shift + Q while it's morphed) and try to mine the schist rock block with it and get that bug, that would effectively be on our hands. Although since I believe the Akashic Tome still holds some information on the books it stores when morphing, that could be a bug with their item and NBT storage (since the Quest book morphed from Akashic Tome is not the same item as the "normal" Quest book without the Akashic Tome, if that makes sense).

I'll close this for now, but if you can test that behavior and confirm it's us, I'll reopen it. Thanks in advance for checking some of this out and sorry for the delays!
