### ISSUE TITLE
[Bug]: Seriously Game Breaking Issue

### ISSUE THREAD

**Issue by Rage-GitHub** [FTBTeam/FTB-Mods-Issues#306]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.8-build.101

### Forge / Fabric version

1.18.2 0.14.6

### What issue are you having?

So I just came across an issue with FTBQuests after loading up my game from editing it last night, which caused an issue with singleplayer to just not load at all. Creating a new world would load me in, the initial world chunks would load but going any further, nothing loads. All AI is frozen, looting chests, breaking blocks, you name it, were all just frozen and broken.

Now, I don't know how my configuration from creating quests would cause this but it's very weird how it happened. No crash report was provided since the game was forcefully closed.

### Crashlogs

https://gist.github.com/Rage-GitHub/c9abee0cbe1940bb86c4065ce01e134b

### Steps to reproduce

1. Create quests with the Quest Additions mod installed
2. Cause some sort of issue that the mod doesn't like while creating quests
3. Notice that using the custom configuration and quest setup, Singleplayer is broken

### Anything else to note?

My custom quest configuration.
[ftbquests.zip](https://github.com/FTBTeam/FTB-Mods-Issues/files/8885334/ftbquests.zip)

**Comment by MichaelHillcox** [comment]
I'll need the crashlog and if possible, the debug.log as well please

**Comment by Raidobw2** [comment]
Is this what you need Michael or would you need more information?
```
[20:37:32] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at net.minecraft.class_3445.method_14952(class_3445.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_3445.method_14950(class_3445.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_3445.<init>(class_3445.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_3448.method_14961(class_3448.java:28) ~[client-intermediary.jar:?]
	at java.util.Map.computeIfAbsent(Map.java:1054) ~[?:?]
	at net.minecraft.class_3448.method_14955(class_3448.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_3448.method_14956(class_3448.java:41) ~[client-intermediary.jar:?]
	at dev.ftb.mods.ftbquests.quest.task.StatTask.submitTask(StatTask.java:110) ~[ftb-quests-fabric-1802.3.8-build.101.jar:?]
	at dev.ftb.mods.ftbquests.quest.task.Task.submitTask(Task.java:261) ~[ftb-quests-fabric-1802.3.8-build.101.jar:?]
	at dev.ftb.mods.ftbquests.quest.ServerQuestFile.playerLoggedIn(ServerQuestFile.java:191) ~[ftb-quests-fabric-1802.3.8-build.101.jar:?]
	at dev.ftb.mods.ftbquests.FTBQuestsEventHandler.playerLoggedIn(FTBQuestsEventHandler.java:106) ~[ftb-quests-fabric-1802.3.8-build.101.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.4.70.jar:?]
	at dev.architectury.event.EventFactory$4.handleInvocation(EventFactory.java:125) ~[architectury-4.4.70.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
	at jdk.proxy2.$Proxy74.accept(Unknown Source) ~[?:?]
	at dev.ftb.mods.ftbteams.data.TeamManager.playerLoggedIn(TeamManager.java:322) ~[ftb-teams-fabric-1802.2.6-build.51.jar:?]
	at dev.ftb.mods.ftbteams.FTBTeams.playerLoggedIn(FTBTeams.java:81) ~[ftb-teams-fabric-1802.2.6-build.51.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.4.70.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.4.70.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
	at jdk.proxy2.$Proxy161.join(Unknown Source) ~[?:?]
	at net.minecraft.class_3324.handler$znf000$placeNewPlayer(class_3324.java:2466) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ehe000$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by MichaelHillcox** [comment]
As this issue is very old and we've pushed a large amount of changes to the mod. Please check if your issue is still present in 1.21 versions of the mod. If it is, please open a new issue with updated information so it's top of our list 👍

Please do not feel obligated to follow on with this issue, we understand that situations change and we do not expect an update from any of our users.
