### ISSUE TITLE
[Bug]: FTB Backups locking up server thread on server shutdown

### ISSUE THREAD

**Issue by Anoyomouse** [FTBTeam/FTB-Mods-Issues#314]
### Mod

FTB Backups

### Mod version

ftbbackups2:1-18.2-1.0.10

### Forge / Fabric version

1.18.2 40.1.47

### Modpack & version

DW20 1.4.1

### What issue are you having?

When we /stop our server after playing, the game locks up after everything has unloaded. after a few hours of the game stuck in this state, i eventually CTRL+C the server and am shown an FTB backups exception

### Crashlogs

net.creeperhost.ftbbackups.org.quartz.SchedulerException: The Scheduler has been shutdown.
        at TRANSFORMER/ftbbackups2@1.0.10/net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler.validateState(QuartzScheduler.java:735)
        at TRANSFORMER/ftbbackups2@1.0.10/net.creeperhost.ftbbackups.org.quartz.core.QuartzScheduler.clear(QuartzScheduler.java:1503)
        at TRANSFORMER/ftbbackups2@1.0.10/net.creeperhost.ftbbackups.org.quartz.impl.StdScheduler.clear(StdScheduler.java:240)
        at TRANSFORMER/ftbbackups2@1.0.10/net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:110)
        at java.base/java.lang.Thread.run(Unknown Source)

### Steps to reproduce

1. Start the server (standalone windows)
2. Play for a while
3. As an opped player type "/stop"
4. See the server shutdown, but never stop executing
5. Press Ctrl+C in the server window
6. Get execption

**Comment by mjevans** [comment]
I encountered this as well ftbbackups2-forge-1.18.2-1.0.11.jar

https://gist.github.com/mjevans/91a173abb00c477e08c66cb3d8c939ac

https://github.com/EnigmaticaModpacks/Enigmatica8/issues/214

**Comment by gigabit101** [comment]
This was fixed a while ago, Update FTB Backups to latest version

**Comment by Raidobw2** [comment]
Closing as this was solved before

Use 1.0.13 and up for the Minecraft version you're playing on
https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2/files
