### ISSUE TITLE
[Bug]: Crash to desktop when using FTB Industrial Contraptions (Forge)

### ISSUE THREAD

**Issue by fire2burn** [FTBTeam/FTB-Mods-Issues#318]
### Mod

FTB Industrial Contraptions (Forge)

### Mod version

ftb-industrial-contraptions-1900.1.6-build.168.jar

### Forge / Fabric version

41.0.35 forge

### What issue are you having?

Crash to desktop when attempting to enter existing world or create new one with FTB Industrial Contraptions (Forge) installed
![game crashed](https://user-images.githubusercontent.com/107639986/174126819-012f8d17-73fa-49a6-88e2-96def5e71a10.jpg)

### Crashlogs

---- Minecraft Crash Report ----
// My bad.

Time: 6/16/22, 5:39 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraftforge.fluids.FluidAttributes net.minecraft.world.level.material.Fluid.getAttributes()'
	at dev.ftb.mods.ftbic.item.FluidCellItem.m_7373_(FluidCellItem.java:133) ~[ftb-industrial-contraptions-1900.1.6-build.168.jar%2389!/:1900.1.6-build.168] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:658) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91316_(Minecraft.java:698) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.searchtree.PlainTextSearchTree.m_235197_(PlainTextSearchTree.java:20) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.FullTextSearchTree.m_214078_(FullTextSearchTree.java:26) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.SearchRegistry$TreeEntry.m_235245_(SearchRegistry.java:61) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.SearchRegistry.m_235235_(SearchRegistry.java:42) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_231374_(Minecraft.java:2409) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1311) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1029) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.ftb.mods.ftbic.item.FluidCellItem.m_7373_(FluidCellItem.java:133) ~[ftb-industrial-contraptions-1900.1.6-build.168.jar%2389!/:1900.1.6-build.168] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:658) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91316_(Minecraft.java:698) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.searchtree.PlainTextSearchTree.m_235197_(PlainTextSearchTree.java:20) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.FullTextSearchTree.m_214078_(FullTextSearchTree.java:26) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.SearchRegistry$TreeEntry.m_235245_(SearchRegistry.java:61) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.searchtree.SearchRegistry.m_235235_(SearchRegistry.java:42) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_231374_(Minecraft.java:2409) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1311) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['fire2burn'/477, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 961, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:448) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2169) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:683) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23103!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, §lEpic Adventures.zip, MYTHIC - 1.19.zip, HYCAR-1.18-5.0.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2296509152 bytes (2190 MiB) / 4206886912 bytes (4012 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0412
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4835
	Graphics card #1 name: NVIDIA GeForce GTX 770
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1184
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 18703.13
	Virtual memory used (MB): 11400.09
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Launched Version: forge-41.0.35
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 770/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/§lEpic Adventures.zip, file/MYTHIC - 1.19.zip, file/HYCAR-1.18-5.0.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['fire2burn'/477, l='ServerLevel[New World22]', x=-59.61, y=61.00, z=76.70]]
	Data Packs: vanilla, mod:forge, mod:journeymap (incompatible), mod:fallingtree, mod:sereneseasons (incompatible), mod:configured (incompatible), mod:bettervillage, mod:backpacked (incompatible), mod:farmingforblockheads (incompatible), mod:guardvillagers (incompatible), mod:ferritecore (incompatible), mod:additionalstructures, mod:globalxp, mod:balm (incompatible), mod:libraryferret, mod:goblintraders (incompatible), mod:clumps (incompatible), mod:mcwbridges, mod:capturetomob, mod:enchdesc (incompatible), mod:jei (incompatible), mod:villagernames, mod:collective, mod:tombstone, mod:bookshelf (incompatible), mod:appleskin, mod:prettybeaches (incompatible), mod:architectury (incompatible), mod:myrtrees (incompatible), mod:ftbic (incompatible)
	World Generation: Experimental
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.19.jar                      |Macaw's Bridges               |mcwbridges                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		CaptureAmob-Forge-1.19-1.0.1.jar                  |Capture a mob                 |capturetomob                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19-11.0.4.jar     |EnchantmentDescriptions       |enchdesc                      |11.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		jei-1.19-forge-11.0.0.203.jar                     |Just Enough Items             |jei                           |11.0.0.203          |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.19-1.0.3.jar                |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.2-1.19.jar                      |Goblin Traders                |goblintraders                 |1.7.2               |DONE      |Manifest: NOSIGNATURE
		villagernames_1.19.0-3.5.jar                      |Villager Names                |villagernames                 |3.5                 |DONE      |Manifest: NOSIGNATURE
		collective-1.19.0-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19-9.0.0+3.jar                     |Clumps                        |clumps                        |9.0.0+3             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5rc2-forge.jar                |Journeymap                    |journeymap                    |5.8.5rc2            |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.19-8.0.0.16.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.19.jar                         |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		BetterVillage-Forge-1.19-1.0.1.jar                |Better Village                |bettervillage                 |1                   |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.7-1.19.jar                         |Backpacked                    |backpacked                    |2.1.7               |DONE      |Manifest: NOSIGNATURE
		tombstone-8.0.0-1.19.jar                          |Corail Tombstone              |tombstone                     |8.0.0               |DONE      |Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19-11.0.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.0.0              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19-14.0.3.jar                   |Bookshelf                     |bookshelf                     |14.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.19-1.5.0.jar                     |Guard Villagers               |guardvillagers                |1.4.2               |DONE      |Manifest: NOSIGNATURE
		architectury-5.7.27-forge.jar                     |Architectury                  |architectury                  |5.7.27              |DONE      |Manifest: NOSIGNATURE
		myrtrees-forge-1.2.0-build.31.jar                 |Myrtrees                      |myrtrees                      |1.2.0-build.31      |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Rex's-AdditionalStructures-1.19-(v.4.0.0).jar     |Additional Structures         |additionalstructures          |4.0.0               |DONE      |Manifest: NOSIGNATURE
		globalxp-1.19-1.10.jar                            |Global XP                     |globalxp                      |1.10                |DONE      |Manifest: NOSIGNATURE
		balm-4.0.0+0.jar                                  |Balm                          |balm                          |4.0.0+0             |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19-3.6.1.jar                        |FallingTree                   |fallingtree                   |3.6.1               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		forge-1.19-41.0.35-universal.jar                  |Forge                         |forge                         |41.0.35             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.19        |DONE      |Manifest: NOSIGNATURE
		prettybeaches-forge-1.19-8.0.0.jar                |Pretty Beaches                |prettybeaches                 |8.0.0               |DONE      |Manifest: NOSIGNATURE
		ftb-industrial-contraptions-1900.1.6-build.168.jar|FTB Industrial Contraptions   |ftbic                         |1900.1.6-build.168  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d314a5f8-21ae-4530-9544-45119032231e
	FML: 41.0
	Forge: net.minecraftforge:41.0.35

### Steps to reproduce

After installing FTB Industrial Contraptions (Forge) the game will crash to desktop when attempting to enter existing worlds or when creating a new one.

**Comment by Gbergz** [comment]
Can confirm, most likely caused by the newest forge versions. .22 works.

**Comment by MichaelHillcox** [comment]
Latest version should have fixed this :+1:

**Comment by Gbergz** [comment]
Still crashes when loading into world
https://gist.github.com/Gbergz/ca860f7608acfb2f086718a7a7b4b722

**Comment by MichaelHillcox** [comment]
Try 180 https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge/files/3836348
