### ISSUE TITLE
[Bug]: ProjectE not working with FTB industrial contraptions

### ISSUE THREAD

**Issue by DerpThePro** [FTBTeam/FTB-Mods-Issues#501]
### Mod

FTB Industrial Contraptions

### Mod version

ftb-industrial-contraptions-1802.1.6-build.197.jar

### Forge / Fabric version

1.18.2 - 40.1.80

### What issue are you having?

I recently downloaded ProjectE because I wanted to use it for future builds and things, just to realise nothing has an EMC value, I looked into the Logs and this is what it shows:

"[14Oct2022 15:08:56.438] [main/ERROR] [projecte/]: Error calculating EMC values
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at com.tagnumelite.projecteintegration.addons.FTBIndustrialContraptionsAddon$AFTBMachineRecipeMapper.getOutput(FTBIndustrialContraptionsAddon.java:57) ~[projecte-integration-1.18.2-5.4.0.jar%23246!/:5.4.0]
	at com.tagnumelite.projecteintegration.addons.FTBIndustrialContraptionsAddon$AFTBMachineRecipeMapper.getOutput(FTBIndustrialContraptionsAddon.java:52) ~[projecte-integration-1.18.2-5.4.0.jar%23246!/:5.4.0]"

I reported this to the ProjectE Discord Server and they told me its a FTB industrial Contraptions issue and to go ask there, so here I am.

I feel it is important to mention they both work on a SinglePlayer world, but on a server, it doesn't want to work

### Steps to reproduce

1. Download FTB industrial Contraptions "ftb-industrial-contraptions-1802.1.6-build.197.jar" and projecte "ProjectE-1.18.2-PE1.0.1.jar"
2. be on a server

### Anything else to note?

I am on a custom modpack but I do not think the mods in it would cause conflicts, due to them working in a survival world, but if requested i could send the modlist.

**Comment by DerpThePro** [comment]
So I fixed it by removing the mod "ProjectE: integration", so no problem
