### ISSUE TITLE
[Bug]:  FTB Quest registering Key Mappings After Events 

### ISSUE THREAD

**Issue by Zelioth** [FTBTeam/FTB-Mods-Issues#519]
### Mod

FTB Quests

### Mod version

FTB-Quests-Forge-1902.4.2-build.116

### Forge / Fabric version

43.1.47

### Modpack & version

Friends United 2.2.7

### What issue are you having?

Recently started using FTB Quests and noticed this error in the logs when starting the pack. These errors can cause the pack to load slower by a bit so I'm trying to point them out to creators when found so they can possibly be fixed :D.

[01Nov2022 22:26:04.957] [Worker-Main9/WARN] [dev.architectury.registry.client.keymappings.forge.KeyMappingRegistryImpl/]: Key mapping key.ftbquests.quests registered after event
java.lang.RuntimeException: null
	at dev.architectury.registry.client.keymappings.forge.KeyMappingRegistryImpl.register(KeyMappingRegistryImpl.java:47) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at dev.architectury.registry.client.keymappings.KeyMappingRegistry.register(KeyMappingRegistry.java) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at dev.ftb.mods.ftbquests.client.FTBQuestsClient.setup(FTBQuestsClient.java:58) ~[ftb-quests-forge-1902.4.2-build.116.jar%23327!/:1902.4.2-build.116]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23115!/:?]
	at jdk.proxy3.$Proxy108.stateChanged(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplClient$ModBasedEventHandler.event(EventHandlerImplClient.java:341) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at dev.architectury.event.forge.__ModBasedEventHandler_event_FMLClientSetupEvent.invoke(.dynamic) ~[architectury-6.3.49-forge.jar%23175!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.47.jar%23572!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.1.47.jar%23571!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

### Steps to reproduce

Install FTB Quests 

### Anything else to note?

Nope. Would just love to see this error fixed. Thank you :D

**Comment by desht** [comment]
Yep, I've seen this happen too. I'll be taking a look into this one.

**Comment by desht** [comment]
Fixed in 1.19
