### ISSUE TITLE
[Bug]: Crash when right-clicking on quest

### ISSUE THREAD

**Issue by Ibaudia** [FTBTeam/FTB-Mods-Issues#560]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.10-build.138.jar

### Forge / Fabric version

1.19.2 0.11.1

### Modpack & version

Sherman's RPG Adventure Pack 1.0.0

### What issue are you having?

I am having an issue where right-clicking on an item while not in editing mode crashes the game. This is repeatable with all quests.

### Crashlogs

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022-11-27 12:43:55
Description: Ticking screen

java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftblibrary.ui.Button.setIcon(dev.ftb.mods.ftblibrary.icon.Icon)" because "this.buttonOpenDependencies" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at dev.ftb.mods.ftbquests.gui.quests.ViewQuestPanel.tick(ViewQuestPanel.java:361)
	at dev.ftb.mods.ftblibrary.ui.Panel.tick(Panel.java:492)
	at dev.ftb.mods.ftbquests.gui.quests.QuestScreen.tick(QuestScreen.java:386)
	at dev.ftb.mods.ftblibrary.ui.ScreenWrapper.tick(ScreenWrapper.java:153)
	at net.minecraft.client.MinecraftClient.method_1572(MinecraftClient:1821)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1821)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.ftb.mods.ftbquests.gui.quests.ViewQuestPanel.tick(ViewQuestPanel.java:361)
	at dev.ftb.mods.ftblibrary.ui.Panel.tick(Panel.java:492)
	at dev.ftb.mods.ftbquests.gui.quests.QuestScreen.tick(QuestScreen.java:386)
	at dev.ftb.mods.ftblibrary.ui.ScreenWrapper.method_25393(ScreenWrapper.java:153)
	at net.minecraft.class_310.method_1572(class_310.java:1821)
	at net.minecraft.class_437.method_25412(class_437.java:489)

-- Affected screen --
Details:
	Screen name: dev.ftb.mods.ftblibrary.ui.ScreenWrapper
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_310.method_1574(class_310.java:1821)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ibaudia'/114, l='ClientLevel', x=-6.57, y=71.00, z=42.56]]
	Chunk stats: 1024, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 12414 game time, 12414 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, all-the-fish.zip, VanillaTweaks_r626030.zip, 3x_Font_1.19.2_1.1.zip, minecraft/supporteatinganimation, charmonium/journeyman, lambdabettergrass/default, Everycomp Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1081375640 bytes (1031 MiB) / 3825205248 bytes (3648 MiB) up to 8053063680 bytes (7680 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2686
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24247.74
	Virtual memory used (MB): 17166.47
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 163.04
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx7680M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		advancedchatcore: AdvancedChatCore 1.19.2-1.5.8
			com_github_darkkronicle_konstruct_addons: addons 2.0.3-build1
			com_github_darkkronicle_konstruct_core: core 2.0.3-build1
			io_github_maowimpl_owo: owo 2.0.0
			org_apache_commons_commons-csv: commons-csv 1.8
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 4.4.2
		advancedchathud: AdvancedChatHUD 1.19.1-1.3.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.17
		alloy_forgery: Alloy Forgery 2.0.17+1.19
		almostunified: AlmostUnified 1.19.2-0.2.4
		amecs: Amecs 1.3.8+mc.1.19-rc2
			amecsapi: Amecs API 1.3.6+mc22w17a
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.2
		another_furniture: Another Furniture 2.1.2-1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.49
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		badpackets: Bad Packets 0.2.1
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.3
		betteranimationscollection: Better Animations Collection 4.0.4
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		bettercombat: Better Combat 1.4.5+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.1
		betterf3: BetterF3 4.0.0
		betterfpsdist: Better FPS distance Mod 1.19.1-2.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 1.4.3
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.8.1
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		boathud: BoatHud 1.1.1
		bookshelf: Bookshelf 16.1.11
		borderlessmining: Borderless Mining 1.1.5+1.19
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.3-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		charmonium: Charmonium 4.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chatsounds: Chat Sounds 1.1.7
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		chesttracker: Chest Tracker 1.1.18
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.13
		chunky: Chunky 1.3.38
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cleancut: CleanCut 1.19.2-5.1-fabric
		clear-skies: Clear Skies 2.0.95
		cleardespawn: Clear Despawn 1.1.10
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 5.16
			fiber: fiber 0.23.0-2
		connectivity: Connectivity Mod 1.19-3.3
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		creativecore: CreativeCore (Fabric) 2.9.1
		criticalib: CriticaLib 1.0.0
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		damageindicator: Damage Indicator 1.0.0
		dark-loading-screen: Dark Loading Screen 1.6.12
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dataattributes: Data Attributes 1.2.7
		deathlog: DeathLog 0.2.11+1.19
		debugify: Debugify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		dragonfight: Dragonfight Mod 1.19.2-2.6
		dragonloot: DragonLoot 1.1.2
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		dynamicfps: Dynamic FPS 2.2.0
		easymagic: Easy Magic 4.3.2
		eatinganimationid: Eating Animation 1.9
		effective: Effective 1.3
		enchantinginfuser: Enchanting Infuser 4.2.2
		enchdesc: EnchantmentDescriptions 13.0.8
		equipmentcompare: Equipment Compare 1.3.1
		everycomp: Every Compat 1.19.2-2.1.4
		exordium: Exordium 1.0.2-mc1.19.2
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.66.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.1+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.3+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.0+a1d87cb890
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.33+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.7+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.10+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.18+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.0+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.13+12bfe4ea90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.15+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.16+12bfe4ea90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.3+3e1ba48e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fallingleaves: Falling Leaves 1.12.4+1.19.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.5
		farmersknives: Farmer's Knives 2.3
		faster_entity_animations: FastAnim 1.5.6
		fastload: Fast Load 2.3.5
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		ftblibrary: FTB Library 1902.3.10-build.156
		ftbquests: FTB Quests 1902.4.3-build.140
			team_reborn_energy: Energy 2.2.0
		ftbteams: FTB Teams 1902.2.9-build.61
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.36
			com_eliotlash_mclib_mclib: mclib 20
		goodall: Goodall 1.1.1
		graveyard: The Graveyard 2.2
		graveyard_biomes: The Graveyard Biomes 1.6
		harvest_scythes: Harvest Scythes 2.5.4+mc1.19.2
		healthoverlay: Health Overlay 7.1.1
		holdthatchunk: Hold That Chunk 2.0.1
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.8
		immersive_armors: Immersive Armors 1.5.0+1.19.2
		impaled: Impaled 1.1.4
		indium: Indium 1.0.9+mc1.19.2
		inmis: Inmis 2.7.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		interactic: Interactic 0.1.11+1.19
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.4.2
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		ironchests: Iron Chests: Restocked 3.1.1
			resourcefullib: Resourceful Lib 1.1.15
		itemfilters: Item Filters 1902.2.9-build.46
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jade: Jade 8.5.1
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.3.3
		lenientdeath: Lenient Death 0.9.1
		letmedespawn: Let Me Despawn fabric-1.0.2
		levelz: LevelZ 1.4.0
		libraryferret: Library ferret 3.0.0
		lightoverlay: Light Overlay 7.0.0
		limitedchunks: Limited Chunkloading Mod 1.19.2-2.6
		lithium: Lithium 0.10.2
		logcleaner: Log Cleaner 1.0.0
		logprot: Logprot Mod 1.19-1.9
		lootintegrations: Loot integration Mod 1.19.1-1.7
		lootr: Lootr 0.4.22.61
		malilib: MaLiLib 0.13.0
		memorysettings: Memorysettings Mod 1.19.2-2.2
		midnightcontrols: MidnightControls 1.7.1+1.19
			midnightlib: MidnightLib 0.6.1
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.0
		moonlight: Moonlight 1.19.2-2.1.9
		morepotions: More Potions 1.0.2
		mousetweaks: Mouse Tweaks 2.22
		mythicmetals: Mythic Metals 0.16.3+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.1
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		netherdepthsupgrade: Nether Depths Upgrade 1.1.0
		nicephore: Nicephore fabric-1.19.x-1.0.0
			com_profesorfalken_jpowershell: jPowerShell 3.1.1
		nmuk: No More Useless Keys 1.0.1+mc1.19
		no_more_purple: No More Purple 1.0.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		notenoughcrashes: Not Enough Crashes 4.2.0+1.19.2
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
		paxi: Paxi 1.19.2-Fabric-3.0
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		player-animator: Player Animator 0.4.0-test4
		presencefootsteps: Presence Footsteps 1.6.3
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		projectiledamage: Projectile Damage Attribute 2.2.0+1.19
		puzzleslib: Puzzles Lib 4.3.12
		qu-enchantments: Qu Enchantments 1.2.4-1.19
			mm: Manningham Mills 2.3
		raknetify: Raknetify (Fabric) 0.1.0+alpha.5.15
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.572
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.2
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpgdifficulty: Rpg Difficulty 1.3.5
		servercore: ServerCore 1.3.3-1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
		shouldersurfing: Shoulder Surfing Reloaded 2.2.16
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		simplyswords: Simply Swords 1.34-1.19.x
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		smoothswapping: Smooth Swapping 0.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.12+mc1.19.2-build.72
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulsweapons: Marium's Soulslike Weaponry 0.9.7
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.16
		spark: spark 1.9.45
		spellbound: Spellbound 1.11.0-test2
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		terrablender: TerraBlender 2.0.1.130
		things: Things 0.2.20+1.19
		thorium: thorium 1.3.2
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		trinkets: Trinkets 3.4.0
		twilightforest: The Twilight Forest 4.2.310
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			porting_lib: Porting Lib 2.0.591+1.19.2
				porting_lib_base: Porting Lib Base 2.0.591+1.19.2
				porting_lib_entity: Porting Lib Entity 2.0.591+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.591+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.591+1.19.2
				porting_lib_models: Porting Lib Models 2.0.591+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.591+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.591+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.591+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.591+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.591+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.591+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.591+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.591+1.19.2
							porting_lib_constants: Porting Lib Constants 2.0.591+1.19.2
						porting_lib_common: Porting Lib Common 2.0.591+1.19.2
			serialization_hooks: Serialization Hooks 0.3.22
		universal-graves: Universal Graves 2.1.3+1.19.2
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			polymer: Polymer (Core) 0.2.17+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
			sgui: sgui 1.1.5+1.19.1
		visuality: Visuality 0.5.5
		vmp: Very Many Players 0.2.0+beta.7.12
		waterdripsound: Drip Sounds 1.19-0.3.0
		whisperwoods: Whisperwoods 1.19-2.1.1
		whydoesmyglasssoundlikethat: Why Does My Glass Sound Like That 1.0.1
		windchimes: Windchimes 1.2.1
		xaerominimapfair: Xaero's Minimap 22.16.0
		xaeroworldmap: Xaero's World Map 1.28.3
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		zoomify: Zoomify 2.8.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: Custom (+17 options changed by user)
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.86, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/all-the-fish.zip (incompatible), file/VanillaTweaks_r626030.zip, file/3x_Font_1.19.2_1.1.zip, minecraft/supporteatinganimation, charmonium/journeyman, lambdabettergrass/default
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Ibaudia'/114, l='ServerLevel[New World]', x=-6.57, y=71.00, z=42.56]]
	Data Packs: vanilla, Fabric Mods, Everycomp Generated Pack, ctov-farmers-delight-compat-pack-1-1.zip, gleaming_recipe.zip (incompatible)
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), FTB Quests (ftbquests), FTB Library (ftblibrary)

### Steps to reproduce

1. Create a quest
2. Switch to non-editing mode
3. Right-click the quest

**Comment by desht** [comment]
Why are you using ftb-quests-fabric-1802.3.10-build.138.jar with a 1.19.2 modpack?  That version of quests is for 1.18.2.

This is the version you need for 1.19.2 (Fabric): https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/4075704

**Comment by desht** [comment]
Having said that, I can reproduce the crash for the latest version of quests, and the fix is easy.

**Comment by Ibaudia** [comment]
Wow, I'm sorry! It was version:
ftb-quests-fabric-1902.4.3-build.140,jar 
I'm glad you were able to fix it!

**Comment by desht** [comment]
Fixed in current quests releases for 1.18/1.19
