### ISSUE TITLE
FTB Chunks NPE

### ISSUE THREAD

**Issue by LordNoisy** [FTBTeam/FTB-Mods-Issues#6]
I'm relaying this issue from:
https://github.com/FTBTeam/FTB-Chunks/issues/182

Basically after making a claim the map begins to crash whenever it's opened rendering FTB chunks unplayable.

**Comment by LordNoisy** [comment]
Sorry for the lack of information as I don't readily have it available, but what you need to know should be in the linked issue

**Comment by Raidobw2** [comment]
Crashing when opening the map. The player must have claimed chunks for the crash to have a chance to occur, I believe.

Mod & Pack version
ftb-chunks-forge-1605.3.1-build.41

Forge / Fabric version, if applicable
Forge

Modpack (with version), if applicable
Enigmatica 6 v0.5.9

Notice Line 34 in the `getCurrent` call
```
java.lang.NullPointerException: Unexpected error
    at dev.ftb.mods.ftbchunks.client.map.MapDimension.getCurrent(MapDimension.java:34) ~[ftbchunks:?] {re:classloading}
    at dev.ftb.mods.ftbchunks.client.LargeMapScreen.<init>(LargeMapScreen.java:61) ~[ftbchunks:?] {re:classloading}
    at dev.ftb.mods.ftbchunks.client.FTBChunksClient.openGui(FTBChunksClient.java:179) ~[ftbchunks:?] {re:classloading,re:mixin}
    at dev.ftb.mods.ftbchunks.client.FTBChunksClient.keyPressed(FTBChunksClient.java:342) ~[ftbchunks:?] {re:classloading,re:mixin}
    at me.shedaniel.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:304) ~[architectury:?] 
```
EventHandler > KeyPressed (m) > openGUI > new LargeMapScreen > getCurrent call

```
public LargeMapScreen() {
		regionPanel = new RegionMapPanel(this);
	     >>>dimension = MapDimension.getCurrent();<<<
		regionPanel.setScrollX(0D);
		regionPanel.setScrollY(0D);
	}
```

Everytime you used a LargeMapScreen you created a new instance, so the problem is from within the constructor somewhere. (ex: a value used during the construction of the object real time at a moment M was incorrect, null, missing params, etc).
So we look into that method which crashed:
```
public static MapDimension getCurrent() {
		if (current == null) {
//L34	  >>>current = MapManager.inst.getDimension(Minecraft.getInstance().level.dimension());<<<
		}
```
I don't know if `Minecraft.getInstance().level.dimension()` can throw an error -- main libs, i assume not/handled.
`inst.getDimension` can throw an error if `MapManager.inst` is not instanciated.

A null happens on line 34, this means that the if from the line before `if (current == null)` went through. There is one line in your code where you can enable that condition to pass because `current` is private `private static MapDimension current;`.

This one line is the method `updateCurrent()` which is only called twice:
![image](https://user-images.githubusercontent.com/17010632/135411227-045a8df6-e232-46ec-834e-d5b15f2eb70a.png)

The one at line 258 is inside `loggedOut`.
The one at line 443 is inside `renderHud`.

From common sense, the method `loggedOut` should not be the faulty one since players intend to keep playing.
`renderHud` indeed would be the one to allow pass to that "if" from earlier, at its line 443 on `updateCurrent`, setting it to null, opening the door (allowing to enter the "if") to where the error will be in a second.
And on the line under, on 444, there is effectively a call to `getCurrent` to restore the instance of the private var `current` in its `MapDimension` class (this enters the "if" where the error was caught looks like).

The original report from E6 was updating from:
`ftb-chunks-forge-1605.3.1-build.24.jar` to `ftb-chunks-forge-1605.3.1-build.41.jar` at maximum and got crashes.
This means the commits between `]7th july 2021, 2nd august 2021]` (after 7 july, up to 2 august included) are the ones that could have introduced that error (according to CurseForge release dates), although on 1 August it was already at build 53, so maybe a bit before.

Right after 7th july on commit `b7e81a2` is where some changes were made to using the various stuff from above, most commonly calling `MapManager.inst` in some new spots that didn't call it before. Hopefully this points towards the solution.

My conclusion: the error probably happens when `renderHud` gets called (justifies client crash as well) and could involve `MapManager.inst` not being instanciated or missing information within its structure (subcalls within `getDimensions`? But stackstrace doesn't say so, it says L34, so `MapManager.inst`), resulting in null pointer on function call. (`null.DoSomething()`)

It's too much code for my brain and i don't know if i pointed you two in the right direction or if i made errors, Lat or Max, but hopefully you reason with what i mentioned and i'm hoping this helps you in the debug.

-R3GEN
