### ISSUE TITLE
[Bug]: FTB Quests crash when log into game

### ISSUE THREAD

**Issue by Creepercdn** [FTBTeam/FTB-Mods-Issues#648]
### Mod

FTB Quests

### Mod version

ftb-quests-fabric-1802.3.13-build.175

### Forge / Fabric version

Quilt 0.17.10

### Modpack & version

Create: Astral

### What issue are you having?

Crash when log into the server

### Crashlogs

Full log: https://0bin.net/paste/dibzdXkm#nKDHbyLg278sfHp6CJdw-NMsNjxeuI0TbatNDKIKByw
Peek:
```
[12:59:23] [Netty Client IO #0/ERROR]: Could not deserialize minecraft:
[12:59:23] [Netty Client IO #0/ERROR]: Encountered exception while handling in channel with name "ftbquests:sync_quests"
java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.theme.QuestTheme.clearCache()" because "dev.ftb.mods.ftbquests.quest.theme.QuestTheme.instance" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at dev.ftb.mods.ftbquests.client.ClientQuestFile.clearCachedData(ClientQuestFile.java:147) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.quest.QuestFile.refreshIDMap(QuestFile.java:308) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.quest.QuestFile.readNetDataFull(QuestFile.java:973) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.net.SyncQuestsMessage.<init>(SyncQuestsMessage.java:18) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:51) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl$1.lambda$receive$0(NetworkManagerImpl.java:100) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl$1.receive(NetworkManagerImpl.java:95) ~[architectury-4.9.84-fabric.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler.receive(ClientPlayNetworking.java:213) ~[fabric-networking-api-v1-1.0.0-beta.28+0.67.0-1.18.2.jar-f9545b88-d885-40c9-a046-6038236c2e3d-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:100) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:41) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:102) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:92) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$gbi000$handleCustomPayload(ClientPlayNetworkHandler:2432) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:60) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:8) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:59:23] [Netty Client IO #0/ERROR]: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbquests.quest.theme.QuestTheme.clearCache()" because "dev.ftb.mods.ftbquests.quest.theme.QuestTheme.instance" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at dev.ftb.mods.ftbquests.client.ClientQuestFile.clearCachedData(ClientQuestFile.java:147) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.quest.QuestFile.refreshIDMap(QuestFile.java:308) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.quest.QuestFile.readNetDataFull(QuestFile.java:973) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.ftb.mods.ftbquests.net.SyncQuestsMessage.<init>(SyncQuestsMessage.java:18) ~[ftb-quests-fabric-1802.3.13-build.175.jar:?]
	at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:51) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl$1.lambda$receive$0(NetworkManagerImpl.java:100) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47) ~[architectury-4.9.84-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl$1.receive(NetworkManagerImpl.java:95) ~[architectury-4.9.84-fabric.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler.receive(ClientPlayNetworking.java:213) ~[fabric-networking-api-v1-1.0.0-beta.28+0.67.0-1.18.2.jar-f9545b88-d885-40c9-a046-6038236c2e3d-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:100) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:41) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:102) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:92) ~[networking-1.1.0-beta.26+1.18.2.jar-a389a686-bb02-4b6e-a28d-306d2310071c-nested.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$gbi000$handleCustomPayload(ClientPlayNetworkHandler:2432) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:60) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:8) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:59:23] [Netty Client IO #0/INFO]: Disconnected from server, EMI data cleared
[12:59:24] [Render thread/INFO]: [inventoryprofilesnext] Loaded 1 external GUI hints
[12:59:24] [Render thread/INFO]: [inventoryprofilesnext] Loaded 738 build-in GUI hints
[12:59:24] [Render thread/INFO]: [inventoryprofilesnext] Effective GUI hints after merge: 739
[12:59:24] [Render thread/INFO]: [ShulkerBoxTooltip] Loading 1 plugin: shulkerboxtooltip
[12:59:24] [Render thread/INFO]: [ShulkerBoxTooltip] Registered 7 providers for mod shulkerboxtooltip
[12:59:24] [Render thread/ERROR]: Error executing task on Client
```

### Steps to reproduce

Log into a server

### Anything else to note?

Minecraft 1.18.2

**Comment by Creepercdn** [comment]
Removing Chimes fixes this bug.

**Comment by desht** [comment]
Yep, your client log is so full of exceptions and errors that I'm surprised it got as far as it did.  This is the one that really broke things:

```
[12:55:34] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
```

Since resourcepack loading failed, FTB Quests couldn't load its theme file from resources, and thus never initialised the theme instance, causing the NPE when it was first referenced.

Not an FTB Quests bug.
