### ISSUE TITLE
[Bug]: Crush when open inventory in Quests GUI

### ISSUE THREAD

**Issue by PydingAbsorber** [FTBTeam/FTB-Mods-Issues#651]
### Mod

FTB Quests

### Mod version

1605.3.6-build.98

### Forge / Fabric version

1.16.5 Forge

### What issue are you having?

Game crushes when pressing E(open inventory) in quests gui.

### Crashlogs

java.lang.NullPointerException
	at com.github.hexomod.worldeditcuife3.aN.a(KeyBinderManager.java:122)
	at net.minecraftforge.eventbus.ASMEventHandler_1037_aN_a_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.client.ForgeHooksClient.onGuiKeyPressedPost(ForgeHooksClient.java:742)
	at net.minecraft.client.KeyboardListener.lambda$keyPress$4(KeyboardListener.java:303)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293)
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at pro.gravit.launcher.DEveLIcIAnZx3h.DeVeLICIaN7dli(Unknown Source)
	at pro.gravit.launcher.DEveLIcIAnZx3h.main(Unknown Source)
	///////////////////////////////////////////
net.minecraft.crash.ReportedException: keyPressed event handler
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:434) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[client-1.16.5-20210115.111550-slim.jar:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5-20210115.111550-slim.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.1.3.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[?:?]
	at pro.gravit.launcher.DEveLIcIAnZx3h.DeVeLICIaN7dli(Unknown Source) ~[Elician.exe:?]
	at pro.gravit.launcher.DEveLIcIAnZx3h.main(Unknown Source) ~[Elician.exe:?]
Caused by: java.lang.NullPointerException
	at com.github.hexomod.worldeditcuife3.aN.a(KeyBinderManager.java:122) ~[worldeditcuife3:3.0.9]
	at net.minecraftforge.eventbus.ASMEventHandler_1037_aN_a_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onGuiKeyPressedPost(ForgeHooksClient.java:742) ~[forge-1.16.5-36.2.34-universal.jar:?]
	at net.minecraft.client.KeyboardListener.lambda$keyPress$4(KeyboardListener.java:303) ~[client-1.16.5-20210115.111550-srg.jar:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[client-1.16.5-20210115.111550-srg.jar:?]

### Steps to reproduce

1.Open FTB Quests book
2.Press E or open inventory

**Comment by desht** [comment]
There is nothing at all in the log to indicate an issue with FTB Quests.  I would suggest speaking with the author of the "worldeditcuife3" mod, whoever that is.
