### ISSUE TITLE
[Bug]: FTB Chunks: Error on Client side in Log, no Crash

### ISSUE THREAD

**Issue by suerion** [FTBTeam/FTB-Mods-Issues#811]
### Mod

FTB Chunks

### Mod version

ftb-chunks-fabric-1902.3.21-build.266

### Forge / Fabric version

1.19.2 Fabric 0.14.20

### What issue are you having?

Got this issue on Client side. No Crash, No Problems, only this error

```
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "state" is null
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.client.map.ChunkUpdateTask.runMapTask(ChunkUpdateTask.java:129)
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.client.map.MapTask.run(MapTask.java:13)
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
20:39:51.528
[20:39:51] [pool-4-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

Spams Randomly in cnsole of client.

**Comment by suerion** [comment]
Hey @desht i had updated to the latest release from 1.19.2, now i get this error on client, no Crash, only in the Logs from the client.

```

[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "state" is null
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.data.HeightUtils.isWater(HeightUtils.java:17)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.data.HeightUtils.getHeight(HeightUtils.java:54)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.client.map.ChunkUpdateTask.runMapTask(ChunkUpdateTask.java:111)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at dev.ftb.mods.ftbchunks.client.map.MapTask.run(MapTask.java:13)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:47:42] [pool-2-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MichaelHillcox** [comment]
As this issue is very old and we've pushed a large amount of changes to the mod. Please check if your issue is still present in 1.21 versions of the mod. If it is, please open a new issue with updated information so it's top of our list 👍

Please do not feel obligated to follow on with this issue, we understand that situations change and we do not expect an update from any of our users.
