### ISSUE TITLE
[Bug]: Questbook won't open on 1.16.5 Forge

### ISSUE THREAD

**Issue by Landon-9999** [FTBTeam/FTB-Mods-Issues#845]
### Mod

FTB Quests

### Mod version

ftb-quests-forge-1605.3.7-build.165.jar

### Forge / Fabric version

36.2.33

### Modpack & version

Engineer's Life 2 (Modified by me)

### What issue are you having?

Quest book will not open on a dedicated server. I was using the previous version before current 1.16.5 version for FTB Quests but that caused a client crash when opening the book. So the most current version won't even open at all.

There is an open issue for this modpack on their Github but it seems to be inactive.
 #https://github.com/Engineers-Life/EL2/issues/191

Architcetury API Version: `architectury-1.32.68.jar`

### Crashlogs

```
[20/06/2023 12:09:29 PM] [main/FATAL] Error executing task on Client
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$7386/1952804668.receive(Unknown Source)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$7386/1952804668.receive(Unknown Source)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:150)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$24140/283779070.accept(Unknown Source)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:29 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:29 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:29 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:30 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$7386/1952804668.receive(Unknown Source)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:150)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$24140/283779070.accept(Unknown Source)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:145)
[20/06/2023 12:09:30 PM] 	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.updateTaskProgress(FTBQuestsNetClient.java:240)
[20/06/2023 12:09:30 PM] 	at dev.ftb.mods.ftbquests.net.UpdateTaskProgressMessage.handle(UpdateTaskProgressMessage.java:46)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$24141/1873131074.run(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$1.queue(NetworkManagerImpl.java:133)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder.lambda$createReceiver$1(MessageDecoder.java:52)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.simple.MessageDecoder$$Lambda$7386/1952804668.receive(Unknown Source)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:150)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$24140/283779070.accept(Unknown Source)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:145)
[20/06/2023 12:09:30 PM] 	at me.shedaniel.architectury.networking.forge.NetworkManagerImpl$$Lambda$7418/646280404.accept(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus$$Lambda$2505/59879483.invoke(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus$$Lambda$2849/219564344.invoke(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$23346/407751779.apply(Unknown Source)
[20/06/2023 12:09:30 PM] 	at java.util.Optional.map(Optional.java:215)
[20/06/2023 12:09:30 PM] 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91)
[20/06/2023 12:09:30 PM] 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904)
[20/06/2023 12:09:30 PM] 	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59)
[20/06/2023 12:09:30 PM] 	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
[20/06/2023 12:09:30 PM] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[20/06/2023 12:09:30 PM] 	at net.minecraft.network.PacketThreadUtil$$Lambda$23579/1565680160.run(Unknown Source)
[20/06/2023 12:09:30 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[20/06/2023 12:09:30 PM] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[20/06/2023 12:09:30 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[20/06/2023 12:09:30 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[20/06/2023 12:09:30 PM] 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948)
[20/06/2023 12:09:30 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[20/06/2023 12:09:30 PM] 	at net.minecraft.client.main.Main.main(Main.java:184)
[20/06/2023 12:09:30 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20/06/2023 12:09:30 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20/06/2023 12:09:30 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20/06/2023 12:09:30 PM] 	at java.lang.reflect.Method.invoke(Method.java:497)
[20/06/2023 12:09:31 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[20/06/2023 12:09:31 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/875761527.call(Unknown Source)
[20/06/2023 12:09:31 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[20/06/2023 12:09:31 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[20/06/2023 12:09:31 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[20/06/2023 12:09:31 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[20/06/2023 12:09:31 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

### Steps to reproduce

Open quest book on dedicated server.

**Comment by desht** [comment]
This is a very long-standing known issue, which I (and others) have never been reproduce.  Although it does get reported from time to time. The cause is that for some reason the server hasn't synced the quest book data to the client when the player connected - but since I've never been able to reproduce the problem, I don't know what that reason is.

Can I confirm you are running your server in online mode, and that your FTB Teams data appears to be valid?  I.e. no server-side errors are logged when your player connects, and commands like `/ftbteams list` return a list of the teams you expect to exist?

**Comment by illya-laifu** [comment]
The same crash just happened to me. Running `Engineer's Life 2` modpack. There are no server side errors, Only the message that the player has lost connection. The output of `/ftbteams info` and `/ftbteams list` produces normal output, with no errors.  

Interestingly enough, but the fix suggested by Landon-9999 - logging into a single player world works with no issues.

**Comment by Moutard3** [comment]
I can confirm I have (with two other people) the same bug on this modpack.
With ftb-quests-forge-1605.3.6 -> crash
With ftb-quests-forge-1605.3.7 -> "Error?! Server doesn't have FTB Quests!" Toast

Logging into singleplayer then going online does work, but has to be done after each client restart.

https://pste.ch/opocemesod
