### ISSUE TITLE
[Bug]: Memory leak still present in FTB Chunks

### ISSUE THREAD

**Issue by embeddedt** [FTBTeam/FTB-Mods-Issues#898]
### Mod

FTB Chunks

### Mod version

ftb-chunks-forge:1902.3.22-build.271

### Forge / Fabric version

1.19.2 43.2.14

### Modpack & version

All The Mods 8 v1.0.22

### What issue are you having?

The memory leak described in https://github.com/FTBTeam/FTB-Mods-Issues/issues/751 still seems to be present when connecting to multiplayer servers. In my case I tested by enabling ModernFix dynamic resources, allocating 4GB of RAM to ATM8, and joining the public ATM8 multiplayer server. With FTB Chunks disabled the baseline memory usage is 2.5GB, indicating that the heap size is more than sufficient. With FTB Chunks enabled, the client stalls shortly after joining the world and eventually crashes due to an OOM error (stacktrace attached below).

I suspect (but have not confirmed via code analysis) that the server is sending the minimap data of all chunks to the client on join and the client does not discard/save this data at the same time, leading to a memory leak.

### Crashlogs

<details>
<summary>The OOM error that occurs</summary>

```
[16:09:59] [Render thread/ERROR] [minecraft/Minecraft]: Out of memory
java.lang.OutOfMemoryError: Java heap space
	at dev.ftb.mods.ftbchunks.client.map.MapRegionData.<init>(MapRegionData.java:31) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:classloading}
	at dev.ftb.mods.ftbchunks.client.map.MapRegion.getDataBlockingNoSync(MapRegion.java:76) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:classloading}
	at dev.ftb.mods.ftbchunks.client.map.MapRegion.getDataBlocking(MapRegion.java:69) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:classloading}
	at dev.ftb.mods.ftbchunks.client.map.UpdateChunkFromServerTask.runMapTask(UpdateChunkFromServerTask.java:27) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:mixin,re:classloading,pl:mixin:A}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.runQueuedTasks(FTBChunksClient.java:1069) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:mixin,re:classloading,pl:mixin:APP:jmi.mixins.json:FTBChunksClientMixin,pl:mixin:A}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient.clientTick(FTBChunksClient.java:1024) ~[ftb-chunks-forge-1902.3.22-build.271.jar%23646!/:1902.3.22-build.271] {re:mixin,re:classloading,pl:mixin:APP:jmi.mixins.json:FTBChunksClientMixin,pl:mixin:A}
	at dev.ftb.mods.ftbchunks.client.FTBChunksClient$$Lambda$30391/0x0000000803739140.tick(Unknown Source) ~[?:?] {}
	at java.lang.invoke.LambdaForm$DMH/0x00000008002a8000.invokeInterface(LambdaForm$DMH) ~[?:?] {}
	at java.lang.invoke.LambdaForm$MH/0x0000000806448c00.invoke(LambdaForm$MH) ~[?:?] {}
	at java.lang.invoke.LambdaForm$MH/0x0000000806455800.invoke(LambdaForm$MH) ~[?:?] {}
	at java.lang.invoke.LambdaForm$MH/0x00000008000d3000.invokeExact_MT(LambdaForm$MH) ~[?:?] {}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin}
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.5.85-forge.jar%23539!/:?] {re:classloading}
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.5.85-forge.jar%23539!/:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23107!/:?] {}
	at jdk.proxy3.$Proxy154.tick(Unknown Source) ~[?:?] {}
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:55) ~[architectury-6.5.85-forge.jar%23539!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_event_ClientTickEvent.invoke(.dynamic) ~[architectury-6.5.85-forge.jar%23539!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23126!/:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$5191/0x0000000800ee6800.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23126!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23126!/:?] {}
```

</details>

### Steps to reproduce

I've mentioned the steps above; nothing is really necessary beyond joining the public multiplayer server, and comparing behavior with FTB Chunks enabled/disabled.

### Anything else to note?

I didn't see any commits on GitHub that would indicate a newer version of the mod has a fix for this, but I didn't test as I don't control the server in use. As far as I know 1902.3.22 (the version I'm using) already includes the recent memory usage improvements.

**Comment by desht** [comment]
Also, what exactly does enabling Modern Fix dynamic resources change?

**Comment by embeddedt** [comment]
> One important question to you is: have you done any memory tuning in the client config? An instance with only 4GB is reasonably considered a potato PC these days,

No, I haven't looked into the config options as I wasn't really sure how to tune them. I had also assumed (possibly incorrectly) the mod would attempt to select reasonable defaults based off the heap size, if such tuning was required. :sweat_smile: I do think it's not great for a minimap mod to consider a 4GB heap "small".

I'd also like to point out that (AFAIK) the minimap is disabled in ATM8, and I had not opened the chunk claiming screen. The OOM seems to occur specifically during an `UpdateChunkFromServerTask` so that's why I am suspecting the client receives data from the server and does not write it out to disk fast enough.

My render distance is usually well below 16 chunks, which means I'd expect there to be at most four 512x512 regions in memory.

> Also, what exactly does enabling Modern Fix dynamic resources change?

This enables block & item models to be loaded and unloaded on the fly instead of persisting in memory and being loaded during game startup. It significantly reduces loading times and memory usage in packs with lots of models (even with FerriteCore installed).
