### ISSUE TITLE
[Bug 1.1.92]: questScreen is null

### ISSUE THREAD

**Issue by itsdinkd** [FTBTeam/FTB-Mods-Issues#915]
### Mod

FTB Quests

### Mod version

1902.5.3-build.268

### Forge / Fabric version

fabric-api-0.76.1+1.19.2

### Modpack & version

AQM2 (Dev version)

### What issue are you having?

Seeing this error in log for client

```java
[09:35:47] [Render thread/ERROR]: [net.minecraft.class_1255#method_18859] Error executing task on Client
java.lang.NullPointerException: Cannot read field "questPanel" because "dev.ftb.mods.ftbquests.client.ClientQuestFile.INSTANCE.questScreen" is null
	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.displayCompletionToast(FTBQuestsNetClient.java:118) ~[ftb-quests-fabric-1902.5.3-build.268.jar:?]
	at dev.ftb.mods.ftbquests.net.DisplayCompletionToastMessage.handle(DisplayCompletionToastMessage.java:32) ~[ftb-quests-fabric-1902.5.3-build.268.jar:?]
	at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52) ~[architectury-6.5.85-fabric.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
[09:35:47] [Render thread/ERROR]: [net.minecraft.class_1255#method_18859] Error executing task on Client
java.lang.NullPointerException: Cannot read field "questPanel" because "dev.ftb.mods.ftbquests.client.ClientQuestFile.INSTANCE.questScreen" is null
	at dev.ftb.mods.ftbquests.client.FTBQuestsNetClient.displayCompletionToast(FTBQuestsNetClient.java:118) ~[ftb-quests-fabric-1902.5.3-build.268.jar:?]
	at dev.ftb.mods.ftbquests.net.DisplayCompletionToastMessage.handle(DisplayCompletionToastMessage.java:32) ~[ftb-quests-fabric-1902.5.3-build.268.jar:?]
	at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52) ~[architectury-6.5.85-fabric.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
```

### Crashlogs

https://gist.github.com/itsdinkd/37bdf13361c5ebbeef6102a5beba2012

### Steps to reproduce

1. Download AQM2
2. Add latest ftb lib and quests
3. Start game
4. check logs

**Comment by desht** [comment]
Fixed in 1902.5.4 release
